### PR TITLE
Change the regex for validate urls for projects to accept .vim projects

### PR DESCRIPTION
**Pull request by edgardleal**
Some projects ( vim plugins ) have url ended by .vim and that url is not accepted.
I changed the regex putting an '(\.vim)?' to create a exception form vim plugins repositories.

### CODE REVIEW

**Comment by bayne** [comment]
Would it  be possible to make the regex more general? Allow all repositories with a `.`

**Comment by edgardleal** [comment]
Good idea. I will send an update tomorrow.

**Comment by edgardleal** [comment]
With the last change, is possible to use - or . as name separator in reporitories. 

I tested with these repositories:
`https://github.com/andyzhau/JavaImp.vim`
`https://github.com/jvenant/vim-java-imports`

**Review by bayne — APPROVED** [review]
Looks great thanks for the PR 👍

**Pull request merged**
